[theme]
primaryColor = "#246c7c"
backgroundColor = "#141c1c"
secondaryBackgroundColor = "#243444"
textColor = "#3abeb6"

[server]
port = 8000
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
